# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Github CI CMake

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: threeal/gcovr-action@latest

    - name: Configure linux_threadx_debug
      working-directory: ${{github.workspace}}
      run: cmake --preset=linux_threadx_debug

    - name: Build linux_threadx_debug
      run: cmake --build --preset=linux_threadx_debug

    - name: Configure linux_test_debug
      working-directory: ${{github.workspace}}
      run: cmake --preset=linux_test_debug

    - name: Build linux_test_debug
      run: cmake --build --preset=linux_test_debug

    - name: Test
      working-directory: ${{github.workspace}}
      run: ctest preset=linux_test_debug --test-dir build_linux_test_debug//
    
    - name: Coverage
      working-directory: ${{github.workspace}}
      run: gcovr -r  . --filter=easy_embedded